resolved error
error TS2564: Property 'item' has no initializer and is not definitely assigned in the constructor.

Solution: added definite assignment assertion which is !: